{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1b91778c",
   "metadata": {},
   "source": [
    "Full Image Transformations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d52c6651",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------- LOAD IMAGE ----------\n",
    "img = cv2.imread(\"images.jpg\")\n",
    "if img is None:\n",
    "    raise FileNotFoundError(\"Image not found.\")\n",
    "\n",
    "rows, cols, ch = img.shape\n",
    "\n",
    "# ---------- 1. TRANSLATION ----------\n",
    "M_trans = np.float32([[1, 0, 100], [0, 1, 50]])\n",
    "dst_trans = cv2.warpAffine(img, M_trans, (cols, rows))\n",
    "\n",
    "# ---------- 2. ROTATION ----------\n",
    "center = (cols // 2, rows // 2)\n",
    "M_rot = cv2.getRotationMatrix2D(center, 45, 1.0)\n",
    "dst_rot = cv2.warpAffine(img, M_rot, (cols, rows))\n",
    "\n",
    "# ---------- 3. SCALING ----------\n",
    "dst_scale = cv2.resize(img, None, fx=1.5, fy=1.5)\n",
    "\n",
    "# ---------- 4. SHEARING ----------\n",
    "M_shear = np.float32([[1, 0.5, 0],\n",
    "                      [0, 1, 0]])\n",
    "dst_shear = cv2.warpAffine(img, M_shear, (cols, rows))\n",
    "\n",
    "# ---------- 5. AFFINE ----------\n",
    "pts1 = np.float32([[50, 50], [200, 50], [50, 200]])\n",
    "pts2 = np.float32([[10, 100], [200, 50], [100, 250]])\n",
    "M_affine = cv2.getAffineTransform(pts1, pts2)\n",
    "dst_affine = cv2.warpAffine(img, M_affine, (cols, rows))\n",
    "\n",
    "# ---------- 6. PERSPECTIVE ----------\n",
    "pts3 = np.float32([[56, 65], [368, 52], [28, 387], [389, 390]])\n",
    "pts4 = np.float32([[0, 0], [300, 0], [0, 300], [300, 300]])\n",
    "M_persp = cv2.getPerspectiveTransform(pts3, pts4)\n",
    "dst_persp = cv2.warpPerspective(img, M_persp, (cols, rows))\n",
    "\n",
    "# ---------- DISPLAY ----------\n",
    "titles = ['Original', 'Translation', 'Rotation',\n",
    "          'Scaling', 'Shear', 'Affine', 'Perspective']\n",
    "\n",
    "images = [\n",
    "    img,\n",
    "    dst_trans,\n",
    "    dst_rot,\n",
    "    dst_scale,\n",
    "    dst_shear,\n",
    "    dst_affine,\n",
    "    dst_persp\n",
    "]\n",
    "\n",
    "plt.figure(figsize=(16, 8))\n",
    "for i in range(len(images)):\n",
    "    plt.subplot(2, 4, i + 1)\n",
    "    plt.imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))\n",
    "    plt.title(titles[i])\n",
    "    plt.axis('off')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c7f00efb",
   "metadata": {},
   "source": [
    "ROI-Based Transformations (Object-Level)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fcac3f49",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------- LOAD IMAGE ----------\n",
    "img = cv2.imread(\"images.jpg\")\n",
    "if img is None:\n",
    "    raise FileNotFoundError(\"Image not found.\")\n",
    "\n",
    "img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "# ---------- OBJECT DETECTION (COLOR-BASED) ----------\n",
    "# Convert to HSV\n",
    "hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)\n",
    "\n",
    "# Yellow color range (tuned for this image)\n",
    "lower_yellow = np.array([15, 80, 80])\n",
    "upper_yellow = np.array([40, 255, 255])\n",
    "\n",
    "# Create mask\n",
    "mask = cv2.inRange(hsv, lower_yellow, upper_yellow)\n",
    "\n",
    "# Clean mask\n",
    "kernel = np.ones((5, 5), np.uint8)\n",
    "mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)\n",
    "mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)\n",
    "\n",
    "# ---------- FIND OBJECT ----------\n",
    "contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
    "\n",
    "if not contours:\n",
    "    raise ValueError(\"No object detected.\")\n",
    "\n",
    "# Take the largest contour (main object)\n",
    "c = max(contours, key=cv2.contourArea)\n",
    "x, y, w, h = cv2.boundingRect(c)\n",
    "\n",
    "roi = img[y:y+h, x:x+w]\n",
    "roi_rgb = cv2.cvtColor(roi, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "# ---------- TRANSFORMATIONS ----------\n",
    "h_roi, w_roi = roi.shape[:2]\n",
    "\n",
    "# 1. Rotation\n",
    "center = (w_roi // 2, h_roi // 2)\n",
    "M_rot = cv2.getRotationMatrix2D(center, 45, 1)\n",
    "rotated = cv2.warpAffine(roi, M_rot, (w_roi, h_roi))\n",
    "\n",
    "# 2. Scaling\n",
    "scaled = cv2.resize(roi, None, fx=1.5, fy=1.5)\n",
    "\n",
    "# 3. Shearing\n",
    "M_shear = np.float32([[1, 0.4, 0],\n",
    "                      [0, 1, 0]])\n",
    "sheared = cv2.warpAffine(roi, M_shear, (w_roi, h_roi))\n",
    "\n",
    "# 4. Affine\n",
    "pts1 = np.float32([[0, 0], [w_roi - 1, 0], [0, h_roi - 1]])\n",
    "pts2 = np.float32([[0, 20], [w_roi - 30, 10], [20, h_roi - 20]])\n",
    "M_affine = cv2.getAffineTransform(pts1, pts2)\n",
    "affine = cv2.warpAffine(roi, M_affine, (w_roi, h_roi))\n",
    "\n",
    "# 5. Perspective\n",
    "pts3 = np.float32([[0, 0], [w_roi, 0], [0, h_roi], [w_roi, h_roi]])\n",
    "pts4 = np.float32([[30, 30], [w_roi - 30, 10], [20, h_roi - 20], [w_roi - 10, h_roi]])\n",
    "M_persp = cv2.getPerspectiveTransform(pts3, pts4)\n",
    "perspective = cv2.warpPerspective(roi, M_persp, (w_roi, h_roi))\n",
    "\n",
    "# ---------- DISPLAY ----------\n",
    "titles = [\n",
    "    \"Original Image\",\n",
    "    \"Detected Object (ROI)\",\n",
    "    \"Rotation\",\n",
    "    \"Scaling\",\n",
    "    \"Shearing\",\n",
    "    \"Affine\",\n",
    "    \"Perspective\"\n",
    "]\n",
    "\n",
    "images = [\n",
    "    img_rgb,\n",
    "    roi_rgb,\n",
    "    cv2.cvtColor(rotated, cv2.COLOR_BGR2RGB),\n",
    "    cv2.cvtColor(scaled, cv2.COLOR_BGR2RGB),\n",
    "    cv2.cvtColor(sheared, cv2.COLOR_BGR2RGB),\n",
    "    cv2.cvtColor(affine, cv2.COLOR_BGR2RGB),\n",
    "    cv2.cvtColor(perspective, cv2.COLOR_BGR2RGB)\n",
    "]\n",
    "\n",
    "plt.figure(figsize=(16, 8))\n",
    "for i in range(len(images)):\n",
    "    plt.subplot(2, 4, i + 1)\n",
    "    plt.imshow(images[i])\n",
    "    plt.title(titles[i])\n",
    "    plt.axis(\"off\")\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
